window.spotsDB = [
  { id: "sea-med-cote-bleue", name: "Cote Bleue", lat: 43.32, lng: 5.12, zoomLevel: 5, type: "sea", species: ["loup", "dorade", "sar"] },
  { id: "sea-med-calanques", name: "Calanques de Marseille", lat: 43.21, lng: 5.45, zoomLevel: 5, type: "sea", species: ["loup", "dorade", "roche"] },
  { id: "sea-corsica-west", name: "Corse ouest", lat: 42.28, lng: 8.69, zoomLevel: 5, type: "sea", species: ["thon", "dorade", "sar"] },
  { id: "sea-brittany-iroise", name: "Mer d'Iroise", lat: 48.36, lng: -4.68, zoomLevel: 5, type: "sea", species: ["loup", "maquereau", "roche"] },
  { id: "sea-biscay-arcachon", name: "Bassin d'Arcachon", lat: 44.64, lng: -1.31, zoomLevel: 5, type: "sea", species: ["loup", "dorade", "maigre"] },
  { id: "fresh-lake-geneva", name: "Lac Leman", lat: 46.39, lng: 6.49, zoomLevel: 5, type: "freshwater", species: ["brochet", "perche", "truite"] },
  { id: "fresh-lake-tahoe", name: "Lake Tahoe", lat: 39.09, lng: -120.05, zoomLevel: 5, type: "freshwater", species: ["truite"] },
  { id: "sea-florida-keys", name: "Florida Keys", lat: 24.92, lng: -80.64, zoomLevel: 5, type: "sea", species: ["tarpon", "snook"] },
  { id: "sea-great-barrier-reef", name: "Great Barrier Reef", lat: -16.92, lng: 145.78, zoomLevel: 5, type: "sea", species: ["tuna", "snapper"] },
  { id: "fresh-amazon-manaus", name: "Amazonas - Manaus", lat: -3.11, lng: -60.03, zoomLevel: 5, type: "freshwater", species: ["catfish", "peacock-bass"] },

  { id: "sea-carry-port", name: "Carry-le-Rouet", lat: 43.33, lng: 5.15, zoomLevel: 8, type: "sea", species: ["dorade", "sar", "roche"] },
  { id: "sea-cassis-port", name: "Cassis", lat: 43.22, lng: 5.54, zoomLevel: 8, type: "sea", species: ["loup", "dorade", "roche"] },
  { id: "sea-quiberon", name: "Quiberon - Cote Sauvage", lat: 47.48, lng: -3.16, zoomLevel: 8, type: "sea", species: ["loup", "maquereau"] },
  { id: "sea-la-rochelle", name: "La Rochelle", lat: 46.05, lng: -1.35, zoomLevel: 8, type: "sea", species: ["loup", "dorade", "maigre"] },
  { id: "sea-saint-jean-luz", name: "Saint-Jean-de-Luz", lat: 43.41, lng: -1.7, zoomLevel: 8, type: "sea", species: ["loup", "dorade"] },
  { id: "fresh-lac-bourget", name: "Lac du Bourget", lat: 45.79, lng: 5.86, zoomLevel: 8, type: "freshwater", species: ["brochet", "perche", "sandre"] },
  { id: "fresh-lac-annecy", name: "Lac d'Annecy", lat: 45.86, lng: 6.14, zoomLevel: 8, type: "freshwater", species: ["brochet", "perche", "truite"] },
  { id: "fresh-rhone-arles", name: "Rhone - Arles", lat: 43.68, lng: 4.63, zoomLevel: 8, type: "freshwater", species: ["sandre", "silure", "carpe"] },
  { id: "sea-ebro-delta", name: "Ebro Delta", lat: 40.72, lng: 0.76, zoomLevel: 8, type: "sea", species: ["loup", "dorade", "thon"] },
  { id: "sea-montauk", name: "Montauk Point", lat: 41.07, lng: -71.86, zoomLevel: 8, type: "sea", species: ["striped-bass", "bluefish"] },
  { id: "fresh-columbia-river", name: "Columbia River", lat: 45.62, lng: -122.67, zoomLevel: 8, type: "freshwater", species: ["salmon", "sturgeon"] },

  { id: "sea-cote-bleue-carro", name: "Carro", lat: 43.3256, lng: 5.0392, zoomLevel: 11, type: "sea", species: ["dorade", "loup", "sar"] },
  { id: "sea-cote-bleue-sausset", name: "Sausset-les-Pins", lat: 43.33, lng: 5.11, zoomLevel: 11, type: "sea", species: ["dorade", "sar", "cephalopodes"] },
  { id: "sea-cote-bleue-redonne", name: "La Redonne", lat: 43.3297, lng: 5.1986, zoomLevel: 11, type: "sea", species: ["dorade", "sar", "roche"] },
  { id: "sea-marseille-frioul", name: "Iles du Frioul", lat: 43.28, lng: 5.3, zoomLevel: 11, type: "sea", species: ["loup", "dorade", "roche"] },
  { id: "sea-marseille-pointe-rouge", name: "Pointe Rouge", lat: 43.24, lng: 5.37, zoomLevel: 11, type: "sea", species: ["loup", "dorade"] },
  { id: "fresh-verdon-sainte-croix", name: "Sainte-Croix - Verdon", lat: 43.79, lng: 6.19, zoomLevel: 11, type: "freshwater", species: ["brochet", "perche", "blackBass"] },
  { id: "fresh-seine-confluence", name: "Seine - confluence", lat: 48.86, lng: 2.33, zoomLevel: 11, type: "freshwater", species: ["sandre", "perche", "silure"] },

  { id: "sea-carry-eaux-salees", name: "Eaux Salees", lat: 43.3297, lng: 5.1747, zoomLevel: 14, type: "sea", species: ["dorade", "sar", "roche"] },
  { id: "sea-couronne-sainte-croix", name: "La Couronne - Sainte-Croix", lat: 43.3282, lng: 5.0635, zoomLevel: 14, type: "sea", species: ["dorade", "loup", "sar"] },
  { id: "sea-carry-cap-rousset", name: "Cap Rousset", lat: 43.3308, lng: 5.1538, zoomLevel: 14, type: "sea", species: ["sar", "roche"] },
  { id: "sea-cassis-port-miou", name: "Port-Miou", lat: 43.206, lng: 5.506, zoomLevel: 14, type: "sea", species: ["loup", "roche"] },
  { id: "fresh-annecy-herbiers-ouest", name: "Annecy - herbiers ouest", lat: 45.859, lng: 6.139, zoomLevel: 14, type: "freshwater", species: ["brochet", "perche"] },
  { id: "fresh-bourget-tombants-nord", name: "Bourget - tombants nord", lat: 45.785, lng: 5.864, zoomLevel: 14, type: "freshwater", species: ["brochet", "perche", "sandre"] },
];
