window.spotsDB = [
  { id: "sea-med-cote-bleue", name: "Cote Bleue", lat: 43.32, lng: 5.12, zoomLevel: 5, type: "sea", species: ["loup", "dorade", "sar"] },
  { id: "sea-med-calanques", name: "Calanques de Marseille", lat: 43.21, lng: 5.45, zoomLevel: 5, type: "sea", species: ["loup", "dorade", "roche"] },
  { id: "sea-corsica-west", name: "Corse ouest", lat: 42.28, lng: 8.69, zoomLevel: 5, type: "sea", species: ["thon", "dorade", "sar"] },
  { id: "sea-brittany-iroise", name: "Mer d'Iroise", lat: 48.36, lng: -4.68, zoomLevel: 5, type: "sea", species: ["loup", "maquereau", "roche"] },
  { id: "sea-biscay-arcachon", name: "Bassin d'Arcachon", lat: 44.64, lng: -1.31, zoomLevel: 5, type: "sea", species: ["loup", "dorade", "maigre"] },
  { id: "fresh-lake-geneva", name: "Lac Leman", lat: 46.39, lng: 6.49, zoomLevel: 5, type: "freshwater", species: ["brochet", "perche", "truite"] },
  { id: "fresh-lake-tahoe", name: "Lake Tahoe", lat: 39.09, lng: -120.05, zoomLevel: 5, type: "freshwater", species: ["truite"] },
  { id: "sea-florida-keys", name: "Florida Keys", lat: 24.92, lng: -80.64, zoomLevel: 5, type: "sea", species: ["tarpon", "snook"] },
  { id: "sea-great-barrier-reef", name: "Great Barrier Reef", lat: -16.92, lng: 145.78, zoomLevel: 5, type: "sea", species: ["tuna", "snapper"] },
  { id: "fresh-amazon-manaus", name: "Amazonas - Manaus", lat: -3.11, lng: -60.03, zoomLevel: 5, type: "freshwater", species: ["catfish", "peacock-bass"] },
  { id: "sea-canary-islands", name: "Canary Islands", lat: 28.29, lng: -16.63, zoomLevel: 5, type: "sea", species: ["tuna", "amberjack", "dentex"] },
  { id: "sea-azores", name: "Azores", lat: 38.54, lng: -28.63, zoomLevel: 5, type: "sea", species: ["tuna", "marlin", "wahoo"] },
  { id: "sea-madeira", name: "Madeira", lat: 32.75, lng: -16.97, zoomLevel: 5, type: "sea", species: ["tuna", "wahoo", "amberjack"] },
  { id: "sea-balearic-islands", name: "Balearic Islands", lat: 39.57, lng: 2.65, zoomLevel: 5, type: "sea", species: ["dentex", "tuna", "dorade"] },
  { id: "sea-gibraltar-strait", name: "Strait of Gibraltar", lat: 36.03, lng: -5.61, zoomLevel: 5, type: "sea", species: ["tuna", "bonito", "sea-bass"] },
  { id: "sea-north-sea", name: "North Sea", lat: 56.2, lng: 3.4, zoomLevel: 5, type: "sea", species: ["cod", "mackerel", "pollock"] },
  { id: "sea-norway-fjords", name: "Norway Fjords", lat: 62.47, lng: 6.15, zoomLevel: 5, type: "sea", species: ["cod", "halibut", "pollock"] },
  { id: "sea-iceland-westfjords", name: "Iceland Westfjords", lat: 65.72, lng: -23.45, zoomLevel: 5, type: "sea", species: ["cod", "halibut", "pollock"] },
  { id: "sea-cape-cod", name: "Cape Cod", lat: 41.68, lng: -70.2, zoomLevel: 5, type: "sea", species: ["striped-bass", "bluefish", "tuna"] },
  { id: "sea-outer-banks", name: "Outer Banks", lat: 35.56, lng: -75.47, zoomLevel: 5, type: "sea", species: ["red-drum", "cobia", "tuna"] },
  { id: "sea-gulf-mexico", name: "Gulf of Mexico", lat: 27.6, lng: -90.9, zoomLevel: 5, type: "sea", species: ["redfish", "snapper", "tarpon"] },
  { id: "sea-baja-california", name: "Baja California", lat: 24.16, lng: -110.33, zoomLevel: 5, type: "sea", species: ["yellowtail", "tuna", "dorado"] },
  { id: "sea-panama-pacific", name: "Panama Pacific", lat: 8.33, lng: -79.11, zoomLevel: 5, type: "sea", species: ["roosterfish", "tuna", "snapper"] },
  { id: "sea-costa-rica-pacific", name: "Costa Rica Pacific", lat: 9.65, lng: -85.16, zoomLevel: 5, type: "sea", species: ["sailfish", "roosterfish", "tuna"] },
  { id: "sea-brazil-southeast", name: "Brazil Southeast", lat: -23.86, lng: -43.13, zoomLevel: 5, type: "sea", species: ["snapper", "tuna", "snook"] },
  { id: "sea-cape-town", name: "Cape Town", lat: -34.18, lng: 18.43, zoomLevel: 5, type: "sea", species: ["yellowtail", "tuna", "kob"] },
  { id: "sea-seychelles", name: "Seychelles", lat: -4.62, lng: 55.45, zoomLevel: 5, type: "sea", species: ["gt", "tuna", "bonefish"] },
  { id: "sea-maldives", name: "Maldives", lat: 3.2, lng: 73.22, zoomLevel: 5, type: "sea", species: ["gt", "tuna", "snapper"] },
  { id: "sea-thailand-andaman", name: "Thailand Andaman", lat: 8.02, lng: 98.29, zoomLevel: 5, type: "sea", species: ["queenfish", "barracuda", "snapper"] },
  { id: "sea-indonesia-komodo", name: "Komodo", lat: -8.58, lng: 119.49, zoomLevel: 5, type: "sea", species: ["gt", "tuna", "snapper"] },
  { id: "sea-japan-sagami", name: "Sagami Bay", lat: 35.17, lng: 139.39, zoomLevel: 5, type: "sea", species: ["tuna", "yellowtail", "seabream"] },
  { id: "sea-new-zealand-bay-islands", name: "Bay of Islands", lat: -35.18, lng: 174.12, zoomLevel: 5, type: "sea", species: ["snapper", "kingfish", "kahawai"] },
  { id: "sea-western-australia", name: "Western Australia", lat: -31.95, lng: 115.74, zoomLevel: 5, type: "sea", species: ["dhufish", "snapper", "tuna"] },
  { id: "fresh-great-lakes", name: "Great Lakes", lat: 44.8, lng: -84.7, zoomLevel: 5, type: "freshwater", species: ["walleye", "bass", "trout"] },
  { id: "fresh-lake-okeechobee", name: "Lake Okeechobee", lat: 26.94, lng: -80.8, zoomLevel: 5, type: "freshwater", species: ["largemouth-bass", "crappie"] },
  { id: "fresh-rio-ebro", name: "Rio Ebro", lat: 41.3, lng: 0.72, zoomLevel: 5, type: "freshwater", species: ["catfish", "zander", "carp"] },
  { id: "fresh-river-thames", name: "River Thames", lat: 51.5, lng: -0.12, zoomLevel: 5, type: "freshwater", species: ["pike", "perch", "barbel"] },
  { id: "fresh-danube-delta", name: "Danube Delta", lat: 45.17, lng: 29.36, zoomLevel: 5, type: "freshwater", species: ["pike", "zander", "catfish"] },
  { id: "fresh-river-nile", name: "Nile - Aswan", lat: 24.09, lng: 32.9, zoomLevel: 5, type: "freshwater", species: ["nile-perch", "catfish", "tilapia"] },
  { id: "fresh-murray-river", name: "Murray River", lat: -34.18, lng: 142.16, zoomLevel: 5, type: "freshwater", species: ["murray-cod", "golden-perch", "carp"] },
  { id: "fresh-lake-victoria", name: "Lake Victoria", lat: -1.05, lng: 33.0, zoomLevel: 5, type: "freshwater", species: ["nile-perch", "tilapia"] },
  { id: "fresh-mekong-delta", name: "Mekong Delta", lat: 10.04, lng: 105.78, zoomLevel: 5, type: "freshwater", species: ["catfish", "snakehead", "carp"] },
  { id: "sea-spain-costa-brava", name: "Costa Brava", lat: 41.9, lng: 3.18, zoomLevel: 5, type: "sea", species: ["sea-bass", "seabream", "dentex"] },
  { id: "sea-spain-valencia-coast", name: "Valencia Coast", lat: 39.42, lng: -0.22, zoomLevel: 5, type: "sea", species: ["sea-bass", "dorade", "leerfish"] },
  { id: "sea-spain-costa-blanca", name: "Costa Blanca", lat: 38.35, lng: -0.42, zoomLevel: 5, type: "sea", species: ["seabream", "amberjack", "dentex"] },
  { id: "sea-spain-costa-del-sol", name: "Costa del Sol", lat: 36.53, lng: -4.62, zoomLevel: 5, type: "sea", species: ["sea-bass", "tuna", "dentex"] },
  { id: "sea-spain-galicia", name: "Galicia Rias", lat: 42.47, lng: -8.82, zoomLevel: 5, type: "sea", species: ["sea-bass", "pollock", "mackerel"] },
  { id: "sea-spain-cantabria", name: "Cantabrian Coast", lat: 43.47, lng: -3.8, zoomLevel: 5, type: "sea", species: ["sea-bass", "bonito", "mackerel"] },
  { id: "fresh-spain-mequinenza", name: "Mequinenza Reservoir", lat: 41.32, lng: 0.31, zoomLevel: 5, type: "freshwater", species: ["catfish", "zander", "black-bass"] },
  { id: "fresh-spain-extremadura", name: "Extremadura Reservoirs", lat: 39.05, lng: -6.36, zoomLevel: 5, type: "freshwater", species: ["black-bass", "barbel", "carp"] },
  { id: "sea-italy-ligurian-coast", name: "Ligurian Coast", lat: 44.1, lng: 8.02, zoomLevel: 5, type: "sea", species: ["sea-bass", "dentex", "amberjack"] },
  { id: "sea-italy-tuscany-coast", name: "Tuscan Coast", lat: 42.72, lng: 10.32, zoomLevel: 5, type: "sea", species: ["seabream", "sea-bass", "dentex"] },
  { id: "sea-italy-sardinia", name: "Sardinia", lat: 40.0, lng: 9.0, zoomLevel: 5, type: "sea", species: ["dentex", "amberjack", "tuna"] },
  { id: "sea-italy-sicily", name: "Sicily", lat: 37.6, lng: 14.0, zoomLevel: 5, type: "sea", species: ["tuna", "dentex", "grouper"] },
  { id: "sea-italy-naples-gulf", name: "Gulf of Naples", lat: 40.72, lng: 14.25, zoomLevel: 5, type: "sea", species: ["seabream", "leerfish", "amberjack"] },
  { id: "sea-italy-adriatic-north", name: "North Adriatic", lat: 44.9, lng: 13.2, zoomLevel: 5, type: "sea", species: ["sea-bass", "seabream", "bluefish"] },
  { id: "sea-italy-puglia", name: "Puglia Coast", lat: 40.62, lng: 17.96, zoomLevel: 5, type: "sea", species: ["grouper", "amberjack", "dentex"] },
  { id: "fresh-italy-lake-garda", name: "Lake Garda", lat: 45.62, lng: 10.67, zoomLevel: 5, type: "freshwater", species: ["pike", "perch", "trout"] },
  { id: "sea-usa-new-england", name: "New England Coast", lat: 42.6, lng: -70.6, zoomLevel: 5, type: "sea", species: ["striped-bass", "bluefish", "tuna"] },
  { id: "sea-usa-long-island", name: "Long Island Sound", lat: 41.08, lng: -72.85, zoomLevel: 5, type: "sea", species: ["striped-bass", "bluefish", "fluke"] },
  { id: "sea-usa-jersey-shore", name: "Jersey Shore", lat: 39.55, lng: -74.25, zoomLevel: 5, type: "sea", species: ["striped-bass", "fluke", "bluefish"] },
  { id: "sea-usa-carolinas", name: "Carolina Coast", lat: 33.95, lng: -77.9, zoomLevel: 5, type: "sea", species: ["red-drum", "speckled-trout", "cobia"] },
  { id: "sea-usa-georgia-south-carolina", name: "Lowcountry Coast", lat: 32.15, lng: -80.55, zoomLevel: 5, type: "sea", species: ["redfish", "flounder", "seatrout"] },
  { id: "sea-usa-florida-atlantic", name: "Florida Atlantic", lat: 27.8, lng: -80.2, zoomLevel: 5, type: "sea", species: ["snook", "tarpon", "sailfish"] },
  { id: "sea-usa-florida-gulf", name: "Florida Gulf", lat: 27.55, lng: -82.95, zoomLevel: 5, type: "sea", species: ["redfish", "snook", "tarpon"] },
  { id: "sea-usa-louisiana-marsh", name: "Louisiana Marsh", lat: 29.28, lng: -90.05, zoomLevel: 5, type: "sea", species: ["redfish", "speckled-trout", "flounder"] },
  { id: "sea-usa-texas-coast", name: "Texas Coast", lat: 27.8, lng: -97.1, zoomLevel: 5, type: "sea", species: ["redfish", "speckled-trout", "flounder"] },
  { id: "sea-usa-california-coast", name: "California Coast", lat: 35.5, lng: -121.2, zoomLevel: 5, type: "sea", species: ["halibut", "rockfish", "yellowtail"] },
  { id: "sea-usa-pacific-northwest", name: "Pacific Northwest", lat: 47.65, lng: -124.3, zoomLevel: 5, type: "sea", species: ["salmon", "halibut", "lingcod"] },
  { id: "sea-usa-alaska-inside", name: "Alaska Inside Passage", lat: 58.3, lng: -134.4, zoomLevel: 5, type: "sea", species: ["salmon", "halibut", "rockfish"] },
  { id: "fresh-usa-lake-michigan", name: "Lake Michigan", lat: 43.9, lng: -87.0, zoomLevel: 5, type: "freshwater", species: ["salmon", "trout", "smallmouth-bass"] },
  { id: "fresh-usa-lake-superior", name: "Lake Superior", lat: 47.7, lng: -87.5, zoomLevel: 5, type: "freshwater", species: ["lake-trout", "walleye", "pike"] },
  { id: "fresh-usa-lake-st-clair", name: "Lake St. Clair", lat: 42.47, lng: -82.72, zoomLevel: 5, type: "freshwater", species: ["muskie", "smallmouth-bass", "walleye"] },
  { id: "fresh-usa-lake-guntersville", name: "Lake Guntersville", lat: 34.42, lng: -86.28, zoomLevel: 5, type: "freshwater", species: ["largemouth-bass", "crappie", "catfish"] },
  { id: "fresh-usa-sam-rayburn", name: "Sam Rayburn", lat: 31.13, lng: -94.1, zoomLevel: 5, type: "freshwater", species: ["largemouth-bass", "crappie", "catfish"] },
  { id: "sea-canada-bc-coast", name: "British Columbia Coast", lat: 50.4, lng: -126.0, zoomLevel: 5, type: "sea", species: ["salmon", "halibut", "rockfish"] },
  { id: "sea-canada-vancouver", name: "Vancouver Coast", lat: 49.18, lng: -123.38, zoomLevel: 5, type: "sea", species: ["salmon", "lingcod", "halibut"] },
  { id: "sea-canada-haida-gwaii", name: "Haida Gwaii", lat: 53.25, lng: -132.0, zoomLevel: 5, type: "sea", species: ["salmon", "halibut", "rockfish"] },
  { id: "sea-canada-nova-scotia", name: "Nova Scotia", lat: 44.5, lng: -63.9, zoomLevel: 5, type: "sea", species: ["striped-bass", "mackerel", "cod"] },
  { id: "sea-canada-newfoundland", name: "Newfoundland", lat: 47.6, lng: -52.7, zoomLevel: 5, type: "sea", species: ["cod", "mackerel", "salmon"] },
  { id: "sea-canada-gulf-st-lawrence", name: "Gulf of St. Lawrence", lat: 48.7, lng: -64.2, zoomLevel: 5, type: "sea", species: ["striped-bass", "cod", "mackerel"] },
  { id: "fresh-canada-lake-ontario", name: "Lake Ontario", lat: 43.7, lng: -77.9, zoomLevel: 5, type: "freshwater", species: ["salmon", "trout", "bass"] },
  { id: "fresh-canada-georgian-bay", name: "Georgian Bay", lat: 45.2, lng: -80.1, zoomLevel: 5, type: "freshwater", species: ["pike", "smallmouth-bass", "walleye"] },
  { id: "fresh-canada-lake-winnipeg", name: "Lake Winnipeg", lat: 52.1, lng: -97.3, zoomLevel: 5, type: "freshwater", species: ["walleye", "pike", "catfish"] },
  { id: "fresh-canada-fraser-river", name: "Fraser River", lat: 49.15, lng: -122.95, zoomLevel: 5, type: "freshwater", species: ["salmon", "sturgeon", "trout"] },

  { id: "sea-carry-port", name: "Carry-le-Rouet", lat: 43.33, lng: 5.15, zoomLevel: 8, type: "sea", species: ["dorade", "sar", "roche"] },
  { id: "sea-cassis-port", name: "Cassis", lat: 43.22, lng: 5.54, zoomLevel: 8, type: "sea", species: ["loup", "dorade", "roche"] },
  { id: "sea-quiberon", name: "Quiberon - Cote Sauvage", lat: 47.48, lng: -3.16, zoomLevel: 8, type: "sea", species: ["loup", "maquereau"] },
  { id: "sea-la-rochelle", name: "La Rochelle", lat: 46.05, lng: -1.35, zoomLevel: 8, type: "sea", species: ["loup", "dorade", "maigre"] },
  { id: "sea-saint-jean-luz", name: "Saint-Jean-de-Luz", lat: 43.41, lng: -1.7, zoomLevel: 8, type: "sea", species: ["loup", "dorade"] },
  { id: "fresh-lac-bourget", name: "Lac du Bourget", lat: 45.79, lng: 5.86, zoomLevel: 8, type: "freshwater", species: ["brochet", "perche", "sandre"] },
  { id: "fresh-lac-annecy", name: "Lac d'Annecy", lat: 45.86, lng: 6.14, zoomLevel: 8, type: "freshwater", species: ["brochet", "perche", "truite"] },
  { id: "fresh-rhone-arles", name: "Rhone - Arles", lat: 43.68, lng: 4.63, zoomLevel: 8, type: "freshwater", species: ["sandre", "silure", "carpe"] },
  { id: "sea-ebro-delta", name: "Ebro Delta", lat: 40.72, lng: 0.76, zoomLevel: 8, type: "sea", species: ["loup", "dorade", "thon"] },
  { id: "sea-montauk", name: "Montauk Point", lat: 41.07, lng: -71.86, zoomLevel: 8, type: "sea", species: ["striped-bass", "bluefish"] },
  { id: "fresh-columbia-river", name: "Columbia River", lat: 45.62, lng: -122.67, zoomLevel: 8, type: "freshwater", species: ["salmon", "sturgeon"] },
  { id: "sea-portugal-algarve", name: "Algarve", lat: 37.02, lng: -8.99, zoomLevel: 8, type: "sea", species: ["sea-bass", "dorade", "tuna"] },
  { id: "sea-morocco-agadir", name: "Agadir", lat: 30.42, lng: -9.63, zoomLevel: 8, type: "sea", species: ["sea-bass", "dentex", "tuna"] },
  { id: "sea-cornwall", name: "Cornwall", lat: 50.12, lng: -5.53, zoomLevel: 8, type: "sea", species: ["bass", "pollock", "mackerel"] },
  { id: "sea-ireland-galway", name: "Galway Bay", lat: 53.2, lng: -9.08, zoomLevel: 8, type: "sea", species: ["pollock", "mackerel", "cod"] },
  { id: "sea-denmark-skagen", name: "Skagen", lat: 57.72, lng: 10.59, zoomLevel: 8, type: "sea", species: ["cod", "mackerel", "sea-trout"] },
  { id: "sea-greece-crete", name: "Crete", lat: 35.21, lng: 24.91, zoomLevel: 8, type: "sea", species: ["dentex", "grouper", "tuna"] },
  { id: "sea-croatia-dalmatia", name: "Dalmatian Coast", lat: 43.51, lng: 16.44, zoomLevel: 8, type: "sea", species: ["dentex", "seabream", "amberjack"] },
  { id: "sea-turkey-bodrum", name: "Bodrum", lat: 37.03, lng: 27.43, zoomLevel: 8, type: "sea", species: ["seabream", "leerfish", "grouper"] },
  { id: "sea-israel-ashdod", name: "Ashdod", lat: 31.8, lng: 34.62, zoomLevel: 8, type: "sea", species: ["leerfish", "grouper", "tuna"] },
  { id: "sea-dubai", name: "Dubai Coast", lat: 25.14, lng: 55.13, zoomLevel: 8, type: "sea", species: ["kingfish", "cobia", "queenfish"] },
  { id: "sea-oman-muscat", name: "Muscat", lat: 23.61, lng: 58.59, zoomLevel: 8, type: "sea", species: ["gt", "tuna", "kingfish"] },
  { id: "sea-india-goa", name: "Goa", lat: 15.49, lng: 73.76, zoomLevel: 8, type: "sea", species: ["barramundi", "snapper", "queenfish"] },
  { id: "sea-sri-lanka-south", name: "Sri Lanka South Coast", lat: 5.95, lng: 80.45, zoomLevel: 8, type: "sea", species: ["tuna", "gt", "sailfish"] },
  { id: "sea-singapore-strait", name: "Singapore Strait", lat: 1.25, lng: 103.85, zoomLevel: 8, type: "sea", species: ["barramundi", "queenfish", "snapper"] },
  { id: "sea-philippines-palawan", name: "Palawan", lat: 9.83, lng: 118.74, zoomLevel: 8, type: "sea", species: ["gt", "tuna", "snapper"] },
  { id: "sea-hawaii-oahu", name: "Oahu", lat: 21.47, lng: -158.1, zoomLevel: 8, type: "sea", species: ["mahi-mahi", "tuna", "trevally"] },
  { id: "sea-sydney-heads", name: "Sydney Heads", lat: -33.84, lng: 151.28, zoomLevel: 8, type: "sea", species: ["kingfish", "snapper", "tailor"] },
  { id: "sea-brisbane-moreton", name: "Moreton Bay", lat: -27.25, lng: 153.25, zoomLevel: 8, type: "sea", species: ["snapper", "flathead", "bream"] },
  { id: "sea-auckland-hauraki", name: "Hauraki Gulf", lat: -36.71, lng: 175.05, zoomLevel: 8, type: "sea", species: ["snapper", "kingfish", "kahawai"] },
  { id: "sea-vancouver-island", name: "Vancouver Island", lat: 49.3, lng: -124.2, zoomLevel: 8, type: "sea", species: ["salmon", "halibut", "rockfish"] },
  { id: "sea-san-diego", name: "San Diego", lat: 32.68, lng: -117.25, zoomLevel: 8, type: "sea", species: ["yellowtail", "tuna", "calico-bass"] },
  { id: "sea-chesapeake-bay", name: "Chesapeake Bay", lat: 38.22, lng: -76.32, zoomLevel: 8, type: "sea", species: ["striped-bass", "bluefish", "red-drum"] },
  { id: "sea-texas-galveston", name: "Galveston", lat: 29.26, lng: -94.79, zoomLevel: 8, type: "sea", species: ["redfish", "speckled-trout", "flounder"] },
  { id: "sea-belize-reef", name: "Belize Barrier Reef", lat: 17.31, lng: -87.53, zoomLevel: 8, type: "sea", species: ["bonefish", "permit", "tarpon"] },
  { id: "sea-colombia-cartagena", name: "Cartagena", lat: 10.39, lng: -75.55, zoomLevel: 8, type: "sea", species: ["tarpon", "snapper", "snook"] },
  { id: "sea-peru-paracas", name: "Paracas", lat: -13.84, lng: -76.27, zoomLevel: 8, type: "sea", species: ["corvina", "bonito", "flounder"] },
  { id: "sea-argentina-mar-del-plata", name: "Mar del Plata", lat: -38.0, lng: -57.54, zoomLevel: 8, type: "sea", species: ["sea-bass", "corvina", "shark"] },
  { id: "fresh-lake-mead", name: "Lake Mead", lat: 36.14, lng: -114.39, zoomLevel: 8, type: "freshwater", species: ["striped-bass", "largemouth-bass", "catfish"] },
  { id: "fresh-lake-erie", name: "Lake Erie", lat: 42.16, lng: -81.25, zoomLevel: 8, type: "freshwater", species: ["walleye", "perch", "smallmouth-bass"] },
  { id: "fresh-river-po", name: "River Po", lat: 45.05, lng: 9.69, zoomLevel: 8, type: "freshwater", species: ["catfish", "zander", "carp"] },
  { id: "fresh-river-rhine", name: "River Rhine", lat: 50.11, lng: 7.73, zoomLevel: 8, type: "freshwater", species: ["zander", "barbel", "pike"] },
  { id: "fresh-river-tagus", name: "River Tagus", lat: 39.46, lng: -8.27, zoomLevel: 8, type: "freshwater", species: ["barbel", "carp", "bass"] },
  { id: "fresh-lake-biwa", name: "Lake Biwa", lat: 35.25, lng: 136.08, zoomLevel: 8, type: "freshwater", species: ["black-bass", "bluegill", "trout"] },
  { id: "fresh-river-parana", name: "Parana River", lat: -31.72, lng: -60.52, zoomLevel: 8, type: "freshwater", species: ["dorado", "surubi", "pacu"] },

  { id: "sea-cote-bleue-carro", name: "Carro", lat: 43.3256, lng: 5.0392, zoomLevel: 11, type: "sea", species: ["dorade", "loup", "sar"] },
  { id: "sea-cote-bleue-sausset", name: "Sausset-les-Pins", lat: 43.33, lng: 5.11, zoomLevel: 11, type: "sea", species: ["dorade", "sar", "cephalopodes"] },
  { id: "sea-cote-bleue-redonne", name: "La Redonne", lat: 43.3297, lng: 5.1986, zoomLevel: 11, type: "sea", species: ["dorade", "sar", "roche"] },
  { id: "sea-marseille-frioul", name: "Iles du Frioul", lat: 43.28, lng: 5.3, zoomLevel: 11, type: "sea", species: ["loup", "dorade", "roche"] },
  { id: "sea-marseille-pointe-rouge", name: "Pointe Rouge", lat: 43.24, lng: 5.37, zoomLevel: 11, type: "sea", species: ["loup", "dorade"] },
  { id: "fresh-verdon-sainte-croix", name: "Sainte-Croix - Verdon", lat: 43.79, lng: 6.19, zoomLevel: 11, type: "freshwater", species: ["brochet", "perche", "blackBass"] },
  { id: "fresh-seine-confluence", name: "Seine - confluence", lat: 48.86, lng: 2.33, zoomLevel: 11, type: "freshwater", species: ["sandre", "perche", "silure"] },
  { id: "sea-lisbon-cascais", name: "Cascais", lat: 38.7, lng: -9.42, zoomLevel: 11, type: "sea", species: ["sea-bass", "dorade", "mackerel"] },
  { id: "sea-mallorca-palma-bay", name: "Palma Bay", lat: 39.5, lng: 2.7, zoomLevel: 11, type: "sea", species: ["dentex", "seabream", "amberjack"] },
  { id: "sea-sicily-palermo", name: "Palermo", lat: 38.13, lng: 13.36, zoomLevel: 11, type: "sea", species: ["dentex", "tuna", "seabream"] },
  { id: "sea-athens-saronic", name: "Saronic Gulf", lat: 37.75, lng: 23.55, zoomLevel: 11, type: "sea", species: ["seabream", "grouper", "leerfish"] },
  { id: "sea-cape-town-false-bay", name: "False Bay", lat: -34.16, lng: 18.63, zoomLevel: 11, type: "sea", species: ["yellowtail", "kob", "tuna"] },
  { id: "sea-miami-biscayne", name: "Biscayne Bay", lat: 25.61, lng: -80.21, zoomLevel: 11, type: "sea", species: ["tarpon", "snook", "bonefish"] },
  { id: "sea-key-west", name: "Key West", lat: 24.55, lng: -81.78, zoomLevel: 11, type: "sea", species: ["tarpon", "permit", "bonefish"] },
  { id: "sea-los-angeles-santa-monica", name: "Santa Monica Bay", lat: 33.93, lng: -118.54, zoomLevel: 11, type: "sea", species: ["calico-bass", "halibut", "yellowtail"] },
  { id: "sea-tokyo-bay", name: "Tokyo Bay", lat: 35.45, lng: 139.82, zoomLevel: 11, type: "sea", species: ["seabass", "flounder", "yellowtail"] },
  { id: "sea-hong-kong", name: "Hong Kong Harbour", lat: 22.27, lng: 114.17, zoomLevel: 11, type: "sea", species: ["seabass", "grouper", "snapper"] },
  { id: "sea-bali-south", name: "Bali South Coast", lat: -8.78, lng: 115.16, zoomLevel: 11, type: "sea", species: ["gt", "snapper", "tuna"] },
  { id: "sea-phuket", name: "Phuket", lat: 7.85, lng: 98.29, zoomLevel: 11, type: "sea", species: ["queenfish", "barracuda", "snapper"] },
  { id: "sea-durban", name: "Durban", lat: -29.86, lng: 31.05, zoomLevel: 11, type: "sea", species: ["kingfish", "tuna", "kob"] },
  { id: "fresh-london-thames-teddington", name: "Thames - Teddington", lat: 51.43, lng: -0.33, zoomLevel: 11, type: "freshwater", species: ["pike", "perch", "barbel"] },
  { id: "fresh-berlin-spree", name: "Spree - Berlin", lat: 52.51, lng: 13.4, zoomLevel: 11, type: "freshwater", species: ["zander", "pike", "perch"] },
  { id: "fresh-amsterdam-canals", name: "Amsterdam Canals", lat: 52.37, lng: 4.9, zoomLevel: 11, type: "freshwater", species: ["zander", "perch", "pike"] },
  { id: "fresh-austin-lady-bird", name: "Lady Bird Lake", lat: 30.26, lng: -97.75, zoomLevel: 11, type: "freshwater", species: ["largemouth-bass", "catfish", "sunfish"] },
  { id: "fresh-bangkok-chao-phraya", name: "Chao Phraya - Bangkok", lat: 13.73, lng: 100.51, zoomLevel: 11, type: "freshwater", species: ["catfish", "snakehead", "carp"] },

  { id: "sea-carry-eaux-salees", name: "Eaux Salees", lat: 43.3297, lng: 5.1747, zoomLevel: 14, type: "sea", species: ["dorade", "sar", "roche"] },
  { id: "sea-couronne-sainte-croix", name: "La Couronne - Sainte-Croix", lat: 43.3282, lng: 5.0635, zoomLevel: 14, type: "sea", species: ["dorade", "loup", "sar"] },
  { id: "sea-carry-cap-rousset", name: "Cap Rousset", lat: 43.3308, lng: 5.1538, zoomLevel: 14, type: "sea", species: ["sar", "roche"] },
  { id: "sea-cassis-port-miou", name: "Port-Miou", lat: 43.206, lng: 5.506, zoomLevel: 14, type: "sea", species: ["loup", "roche"] },
  { id: "fresh-annecy-herbiers-ouest", name: "Annecy - herbiers ouest", lat: 45.859, lng: 6.139, zoomLevel: 14, type: "freshwater", species: ["brochet", "perche"] },
  { id: "fresh-bourget-tombants-nord", name: "Bourget - tombants nord", lat: 45.785, lng: 5.864, zoomLevel: 14, type: "freshwater", species: ["brochet", "perche", "sandre"] },
];
